name: Release
on:
  push:
    branches:
      - release
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: npm i
      - name: Build and test
        run: npm start validate

  Publish:
    needs: Validate
    runs-on: ubuntu-latest
    env:
      GITHUB_REGISTRY_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Configure Git
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - name: Install
        run: npm i
      - name: Release
        run: npm run release -- patch --ci --no-git.push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
